// Generated by CoffeeScript 1.9.3
(function() {
  var CHANNEL, db, redis;

  redis = require('redis').createClient();

  db = require('./database');

  CHANNEL = 'kgraph';

  redis.on('message', function(channel, message) {
    var graph;
    if (channel === CHANNEL) {
      graph = JSON.parse(message);
      console.log('');
      console.log("Processing source " + graph.id + "...");
      return db.update_subgraph(graph, function() {
        return console.log('...done.');
      });
    }
  });

  redis.subscribe(CHANNEL);

  console.log("Subscribed to redis channel " + CHANNEL + ".");

  console.log("Waiting for update requests...");

}).call(this);
